### ISSUE TITLE
add link to github

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/bestiarium#10]
provide a link from the app to this github repo either in the footer or the header/nav bar

**Comment by pirnr81** [comment]
already done

**Comment by pirnr81** [comment]
![image](https://user-images.githubusercontent.com/62375224/144850360-5f7f75d4-bfaa-45d9-b6fd-18cbfdc95858.png)

footer, top left

**Comment by csae8092** [comment]
sorry!
