### ISSUE TITLE
API produces invalid TEI

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/bestiarium#13]
- [x] `@lang` must be in xml namespace
- [x] put `@broken / @reverse` into `@ana` attribute
- [x] rename `tei:div[parent::tei:ab]` to `tei:seg`

test files + xslt fix cf. https://gitlab.com/acdh-oeaw/bestiarium-mesopotamicum/webapp/-/issues/1

**Comment by pirnr81** [comment]
hab grad mit diesen tasks rumgespielt, naive frage:
für punkt 1 bezüglich @lang, muss man da einfach in z.153 von reconstruction.py ab.attrib["lang"] = self.rdg_type in ab.attrib["xml:lang"] = self.rdg_type umändern?
punkt 2 in position.py z.83 bzw 86 von lb.attrib["broken"] = "True" zu lb.attrib["ana"] = "Broken" /bzw Reverse adaptieren?
