### ISSUE TITLE
https://github.com/acdh-oeaw/bestiarium/blob/master/omens/views.py#L103

### ISSUE THREAD

**Issue by pirnr81** [acdh-oeaw/bestiarium#7]
warum wird nix angezeigt? check xslt!

**Comment by pirnr81** [comment]
there seem to be different TEIs at work. using L103, instead of L102  we can visualize the tei:note with the threecolumn.xsl stylesheet (but nothing else) --> write a second stylesheet seems to be the easiest solution

**Comment by csae8092** [comment]
no TEI is stored any more for chapter as of closing #5;
